docker/keycloak/collectivo.json
In order to be able to login publicly into keycloak via collectivo-ux, we need a separate client with different settings than collectivo.
=> add collectivo-ux config for keycloak

Dockerfile, README.md, collectivo-test-app/test_extension/apps.py, collectivo/ux/utils.py
This PR adds menu items to the test_extension
To get microfrontends:
```
curl -X 'GET' \
'http://127.0.0.1:8000/api/ux/v1/microfrontends/' \
-H 'accept: application/json'
```
To get menuitems:
```
curl -X 'GET' \
'http://127.0.0.1:8000/api/ux/v1/menu-items/' \
-H 'accept: application/json'
```
=> Register menuitems in test extension

collectivo/auth/middleware.py, collectivo/auth/userinfo.py
This PR fixes a mistake in the middleware that converted all userinfo attributes into tuples.
=> Fix userinfo

collectivo/devtools/populate.py, collectivo/members/serializers.py
This PR adds additional data to the test population
=> Add more data to test users

collectivo/members/tests/test_members.py, collectivo/members/views.py
This PR adds the email automatically to a new member after registration
=> Add email automatically

collectivo/members/urls.py
Add the endpoints
- members/skills
- members/groups
=> Add endpoints for groups and skills

docker-compose.dev.yml, docker-compose.yml
This should solve random problems with git and docker.
=> Use a prebuild docker container for collectivo-ux

collectivo/apps.py
Create a log entry when the server starts, displaying the version of collectivo
=> log version

collectivo/members/views.py
Catch error if a member is deleted but doesn't have the members_user role.
=> Fix members delete

collectivo/auth/keycloak/models.py, collectivo/auth/keycloak/views.py
This PR fixes a mistake in the keycloak view so that the keycloak API is not required on startup.
It also improves the authentication module so that it can handle the case where a user has an invalid keycloak UUID.
=> Better uuid check

collectivo/emails/serializers.py, collectivo/version.py
Solve some errors caused by the EmailTemplate Serializer
=> Hotfix emails

README.md
Trivial, but my first contribution :)
=> Update links for the API docs in the README

collectivo/tags/setup.py
=> Tags example data

docker-compose.yml, docker/keycloak/Dockerfile
This solves #95 and #94. Dear @Shoadi can you try if this solves the problem for you?
=> Add healthchecks to docker compose

collectivo/memberships/serializers.py, collectivo/memberships/tests.py, collectivo/memberships/urls.py, collectivo/memberships/views.py
Allow users to change their number of shares to a higher number
=> Allow changing shares

collectivo/auth/keycloak/setup.py, collectivo/core/setup.py, collectivo/core/signals.py, collectivo/core/tests/test_core.py, collectivo/emails/tests.py
The first letter of user's first and last name are automatically uppercased.
=> Capitalize names

collectivo/memberships/serializers.py, collectivo/memberships/urls.py, collectivo/memberships/views.py, collectivo/tags/serializers.py, collectivo/tags/tests.py, collectivo/tags/urls.py, collectivo/tags/views.py
New endpoints for the profiles view in https://github.com/MILA-Wien/collectivo-ux/pull/78
=> Add profiles

docker-compose.yml
This corresponds to  https://github.com/MILA-Wien/collectivo-ux/pull/88 and https://github.com/MILA-Wien/collectivo-mila/pull/43/commits/3702ffaaf37fc5abb580c0733e5ac686614d1bf6
=> make env vars consistent

collectivo/core/schedules.py, collectivo/core/tasks.py, collectivo_app/collectivo_app/celery.py, docs/development.md, docs/extensions/components.md
- Add system for adding periodic tasks
- Fix core ping task
- Add celery infos to docs
=> Support periodic tasks

.github/workflows/build_and_test.yml, collectivo/auth/keycloak/apps.py, collectivo/auth/keycloak/models.py, collectivo/auth/keycloak/setup.py, collectivo/auth/keycloak/signals.py, collectivo/core/models.py, collectivo/core/serializers.py, collectivo/core/setup.py, collectivo/core/tests/test_core.py, collectivo/dashboard/views.py, collectivo/emails/setup.py, collectivo/emails/views.py, collectivo/memberships/setup.py, collectivo/menus/models.py, collectivo/menus/serializers.py, collectivo/payments/setup.py, collectivo/payments/views.py, collectivo/profiles/setup.py, collectivo/profiles/signals.py, collectivo_app/collectivo.yml, requirements.txt
- Menus no longer appear double if in multiple groups
- Groups can be edited again after creation
- Permissions have been improved
- Keycloak sync has been improved
=> Small fixes

collectivo/memberships/serializers.py, collectivo/version.py
This makes it possible to edit tags in the membership table
=> Fix memberships tags update
